name: Daily ETL RUN

on:
  schedule:
    - cron: "0 6  * * *"   # Runs daily at 06:00 UTC (08:00 Johannesburg)
  workflow_dispatch:

jobs:
  run-etl:
    name: Run ETL Job
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.11"
      DB_HOST: ${{ secrets.AWS_DB_HOST }}
      DB_USER: ${{ secrets.AWS_DB_USER }}
      DB_PORT: ${{ secrets.AWS_DB_PORT }}
      DB_NAME: ${{ secrets.AWS_DB_NAME }}
      DB_PASSWORD: ${{ secrets.AWS_DB_PASSWORD }}
      API_KEY: ${{ secrets.API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping dependency installation."
          fi

      - name: Run Python syntax check
        run: |
          python -m py_compile $(git ls-files '*.py')

      # - name: Run ETL Script_extract
      #   run: |
      #     python Python_Scripts/Data_extraction.py

      - name: Run ETL Script_load
        run: |
          python Python_Scripts/Data_load.py

      - name: Success message
        if: success()
        run: echo "ETL run completed successfully."

      - name: Failure message
        if: failure()
        run: echo "ETL run failed."
